---
- hosts: all
  tasks:
  - name: 'install dependencies'
    apt:
      name: "{{ item }}"
      state: latest
    become: yes
    with_items: 
      - php
      - nginx

  - name: 'delete apache2'
    apt:
      name: apache2
      state: absent
    become: yes
